upgrade to Elasticsearch 5.0
Upgrade to Elasticsearch 5.0 had some obstacles:

= Strict usage of Log4j 2 and dropped SLF4J support

> commit db86ede456d2d00396e196d911cb56aab84b26ba
> Merge: 7c47325 d9064f4
> Author: Jason Tedor <jason@tedor.me>
> Date:   Wed Aug 31 23:34:40 2016 -0400
>
>    Merge pull request #20235 from jasontedor/log4j2
>
>    Introduce Log4j 2

Usage of 'log4j-to-slf4j' module [1] yields to a
`java.lang.ClassCastException`:

```
java.lang.ClassCastException: org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
  at org.elasticsearch.node.Node.close(Node.java:738)
  at com.github.agebhar1.facelasticq.service.elasticsearch.EmbeddedNode.close(EmbeddedNode.java:88)
  at com.github.agebhar1.facelasticq.service.elasticsearch.EmbeddedNodeTest.elasticsearch_is_running(EmbeddedNodeTest.java:96)
```
Which one originated in `org.elasticsearch.node.Node:738`:
```
724:  final String log4jShutdownEnabled = System.getProperty("es.log4j.shutdownEnabled", "true");
725:  final boolean shutdownEnabled;
726:  switch (log4jShutdownEnabled) {
727:    case "true":
728:      shutdownEnabled = true;
729:      break;
730:    case "false":
731:      shutdownEnabled = false;
732:      break;
733:    default:
734:      throw new IllegalArgumentException(
735:        "invalid value for [es.log4j.shutdownEnabled], was [" + log4jShutdownEnabled + "] but must be [true] or [false]");
736:  }
737:  if (shutdownEnabled) {
738:    LoggerContext context = (LoggerContext) LogManager.getContext(false);
739:    Configurator.shutdown(context);
740:  }
```
Set system property `es.log4j.shutdownEnabled` to `false` skips
the shutdown of Log4j 2.

= Remove `node.mode` and `node.local` settings

> commit 5616251f22be3824e44f634de83934e7157a8f29
> Author: Simon Willnauer <simon.willnauer@elasticsearch.com>
> Date:   Thu Jul 14 13:21:10 2016 +0200
>
>    Remove `node.mode` and `node.local` settings (#19428)
>
>    Today `node.mode` and `node.local` serve almost the same purpose, they
>    are a shortcut for `discovery.type` and `transport.type`. If `node.local: true`
>    or `node.mode: local` is set elasticsearch will start in _local_ mode which means
>    only nodes within the same JVM are discovered and a non-network based transport
>    is used. The _local_ mode it only really used in tests or if nodes are embedded.
>    For both, embedding and tests explicit configuration via `discovery.type` and `transport.type`
>    should be preferred.
>
>    This change removes all the usage of these settings and by-default doesn't
>    configure a default transport implemenation since netty is now a module. Yet, to make
>    the user expericence flawless, plugins or modules can set a `http.type.default` and
>    `transport.type.default`. Plugins set this via `PluginService#additionalSettings()`
>    which enforces _set-once_ which prevents node startup if set multiple times. This means
>    that our distributions will just startup with netty transport since it's packaged as a
>    module unless `transport.type` or `http.transport.type` is explicitly set.
>
>    This change also found a bunch of bugs since several NamedWriteables were not registered if a
>    transport client is used. Now that we don't rely on the `node.mode` leniency which is inherited
>    instead of using explicit settings, `TransportClient` uses `AssertingLocalTransport` which detects these problems since it serializes all messages.

= Modularized (Netty) Transport

> commit 048e4416e7051b0f9daa500f516abfb9c7a00e88
> Author: Simon Willnauer <simonw@apache.org>
> Date:   Mon Jul 11 22:00:45 2016 +0200
>
>    Move netty transport and http into a module
>
>    This moves all netty code and it's dependency into a module.

= Remove NodeBuilder

> commit 6f166dd0fff5421bb81cd102fc84360fb43e6b9a
> Author: Ryan Ernst <ryan@iernst.net>
> Date:   Wed Dec 9 23:57:14 2015 -0800
>
>    Remove NodeBuilder
>
>    The NodeBuilder is currently used to construct a Node. However, this is
>    really just yet-another-builder that wraps around a Settings.Builder
>    witha couple convenience methods. But there are very few uses of these
>    convenience methods.  This change removes NodeBuilder, in favor of just
>    using the Node constructor.

[1] https://logging.apache.org/log4j/2.0/log4j-to-slf4j/index.html